python: '3.10'
install: 'pip install django && pip install djangorestframework && pip install django-filter && pip install django-cors-headers && pip install drf-spectacular && pip install drf-spectacular-sidecar && pip install pandas && pip install openpyxl && pip install PyJWT'
# install: 'pip install djangorestframework'
# install: 'pip install django-filter'
# install: 'pip install django-cors-headers'
# install: 'pip install drf-spectacular'
# install: 'pip install drf-spectacular-sidecar'
# install: 'pip install pandas'
# install: 'pip install openpyxl'
# install: 'pip install djangorestframework-cs'
# install: 'pip install PyJWT'
